### ISSUE TITLE
Move to bluebird

### ISSUE THREAD

**Issue by shernshiou** [depoio/node-telegram-bot#13]
Compared to Q which we are using now, bluebird has better performance and compatibility.

**Comment by Jokero** [comment]
Use native promises by default

**Comment by shernshiou** [comment]
@Jokero planning for this.

**Comment by kaminoo** [comment]
@shernshiou @Jokero +1 for using native promises that come easily with Node v4+

**Comment by shernshiou** [comment]
Closed in favor of native promise #65
