### ISSUE TITLE
Multipart stream parameter

### ISSUE THREAD

**Issue by Christilut** [depoio/node-telegram-bot#14]
I noticed you removed the stream parameter from the multipart method. Filepath as parameter is more user friendly but I am missing the stream parameter since I download files and forward it to Telegram.

I quick and dirty patched it like this for now:
```
//    var file = options.files[key]
//     , filename = path.basename(file)
//      , stream = fs.createReadStream(file);

var file = options.files[key];
var stream = file.stream;
var filename = file.filename;
```

A nicer way to handle stream as parameter would be great

**Comment by shernshiou** [comment]
Ahh.. I am currently reimplement a readable way for this part. Thanks for the headsup!

**Comment by shernshiou** [comment]
Hello, I have implemented the feature you have requested. Please try it out. I appreciate your feedback. The method of implementing stream can be found at echobot sample. 
fc4a3f7e73789f523368a6bb40cfb73ced5a6038
