### ISSUE TITLE
Handle Telegram outage gracefully

### ISSUE THREAD

**Issue by Christilut** [depoio/node-telegram-bot#16]
Telegram was under DDOS yesterday and my bots got this error:  
```
{ [Error: socket hang up] code: 'ECONNRESET' }
```

I think the best place to handle this is in your library. Maybe retry until connectable again? Is there a on-error event?

**Comment by shernshiou** [comment]
Good suggestion. I will implement the retry at open method. Thanks

**Comment by shernshiou** [comment]
@Christilut hey, you can now adjust maxattempt. Default attempt will be 5 times.
