### ISSUE TITLE
Command parsing

### ISSUE THREAD

**Issue by kaminoo** [depoio/node-telegram-bot#21]
Hi!
Love the library.
Could you make some sort of config parameter to enable/disable command parsing?
I'm currently handling this on my own, and if for every message you parse it, it would allow for a loss in performance.
If needed I can contribute with a pull-request for this.
Thanks.
Sebastian

**Comment by shernshiou** [comment]
@kaminoo Sure you can. Look forward for your pull request.

**Comment by shernshiou** [comment]
You can now add options parseCommand and set it to false to disable command parsing.

**Comment by kaminoo** [comment]
Thanks man! Sorry for not sending the pull request, I've been swamped!

**Comment by shernshiou** [comment]
@kaminoo no worries man. I've been swamped until today.
