### ISSUE TITLE
Getting timeouts when trying to send images

### ISSUE THREAD

**Issue by SyRenity** [depoio/node-telegram-bot#25]
Trying to send a PNG image, getting a timeout message:

<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>

The URL is:
https://api.telegram.org/BOT_API_KEY/sendPhoto

Any idea why this happens?

**Comment by shernshiou** [comment]
@SyRenity can you show me your code snippet?

**Comment by SyRenity** [comment]
```
function sendPhoto(to, stream, filename) {
  return bot.sendPhoto({
    chat_id: to,
    caption: 'test',
    files: {
      photo: {
        stream: stream,
        filename: filename
      }
    }
  })
}
```

**Comment by SyRenity** [comment]
I actually tried the latest version as well, and it gave me the same result.

I'm using the one with separate stream, as it allows me to pipe a result without using the disk in the middle.

**Comment by shernshiou** [comment]
@SyRenity I am looking into it. Thanks

**Comment by shernshiou** [comment]
@SyRenity I have tested with stream

```
bot.sendPhoto({
  chat_id: 2229032,
  caption: 'Tester',
  files: {
    filename: 'logo.png',
    stream: fs.createReadStream('./examples/logo.png')
  }
}, function (err, msg) {
  console.log(err);
  console.log(msg);
});
```

**Comment by SyRenity** [comment]
Which version this was tried with?

I'm still getting the time-out error on both the 0.0.14 that I use, and on the latest 0.1:

<html>
<head><title>504 Gateway Time-out</title></head>
<body bgcolor="white">
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx/1.6.2</center>
</body>
</html>

Is the stream object has to have any specific proprieties to work?

**Comment by SyRenity** [comment]
@shernshiou Found the issue, I was simply have not waited until the image creator (QR in this case) finished writing to disk.

Any way to pipe the image creator output to sendPhoto directly, bypassing the disk completely?

**Comment by shernshiou** [comment]
@SyRenity not at the moment. How about contributing for a pull request?

**Comment by SyRenity** [comment]
@shernshiou I will check it once I have some time.

**Comment by icebergyy** [comment]
Was this resolved? I am having issues with 504's when sending images as well
