### ISSUE TITLE
Commands on group chats

### ISSUE THREAD

**Issue by webnetedgar** [depoio/node-telegram-bot#30]
Hi, I'm new here (also started to learn how to code a few weeks ago) and I have a doubt (maybe newbie question, but still):

How can I set my bot to answer group chat commands? Because when I send a command /help on a private chat it works correctly, but when my bot is in a group with another bots, the message is sent as: /help@MyBotUsername, and it doesn't answer.

Any help or explanation would be appreciated, thanks and sorry for any mistake. :)

**Comment by shernshiou** [comment]
try listen to 'help@MyBotUsername' ?

**Comment by webnetedgar** [comment]
Thats possible, but I have almost 40 commands listed 2 times (one with "/command" and another with "[emoji] Command" to custom keyboard), no way to listen every "/help+something" directly? If no, I'll have to put it manually.

**Comment by shernshiou** [comment]
@webnetedgar I guess you need to listen to 'message' and match 

````javascript
message.text.split(' ', 2)[0]
```

**Comment by fivepointseven** [comment]
It would be nice idea to specify botName on initialization along the token and match commands according to it. I'll try in the evening and will throw you a pull request if it'll work

**Comment by webnetedgar** [comment]
Thank you a lot guys, it should work, will try it later today!
