### ISSUE TITLE
Bot analytics integration

### ISSUE THREAD

**Issue by ollmer** [depoio/node-telegram-bot#34]
Hello!
I`m a developer of the analytics service for telegram bots https://github.com/botanio/sdk

I want to offer integrate our sdk to this wrapper, so bot developer can get some analytics without much efforts. Is anyone interested in such enhancement?

**Comment by fivepointseven** [comment]
Hi 
I already integerated botan.io into my bots made on this library and I totally support the idea of adding it to the library itself

**Comment by strikeentco** [comment]
Hello!
I just finished writing my library ([Teabot](https://github.com/strikeentco/teabot)). This is not just a wrapper over the API.
Teabot already supports botan.io analytics, also supported Redis and Aerospike as storage.

I hope this library will find its audience and will be developed further with the help of the community.

Do not consider for ad :)

**Comment by shernshiou** [comment]
Sure. What can I help?

**Comment by ollmer** [comment]
I think it should look like this
```javascript
var bot = new Bot({
  token: 'TOKEN HERE'
})
.enableAnalytics(botan_api_key)
.on('message', function (message) {
  console.log(message);
})
.start();
```
If .enableAnalytics(botan_api_key) called, all messages should be sent to botan service as events before passing them to the callback.
I can make a pull request if you agreed.

**Comment by shernshiou** [comment]
sure no problem!

**Comment by ollmer** [comment]
Ok, thanks! I`m going to code it this weekend and made pull request then.
