### ISSUE TITLE
Add new getFile API

### ISSUE THREAD

**Issue by pennyfx** [depoio/node-telegram-bot#47]
https://core.telegram.org/bots/api#getfile

**Comment by kaminoo** [comment]
+1 for this!

**Comment by shernshiou** [comment]
@pennyfx @kaminoo in the pipeline

**Comment by shernshiou** [comment]
@pennyfx @kaminoo I have committed an experimental getfile feature. Please go ahead and try it out

ee25c1f942e834421c0c68fe3e12de29ccce0dc7

**Comment by kaminoo** [comment]
@shernshiou awesome! Will try it out soon! Thanks!

**Comment by kaminoo** [comment]
@shernshiou I've taken a look at the implementation you did. I would suggest that the getFile method you did saves the file locally only as an alternative. I see you library as a means of creating something bigger. In my case for example, I have no need to download the file but to transfer the URL to someone else. Could you add that?

**Comment by shernshiou** [comment]
@kaminoo sure.
