### ISSUE TITLE
sendPhoto method

### ISSUE THREAD

**Issue by Kaos1337** [depoio/node-telegram-bot#5]
Hello,
thank you for your library, I need help about the use of the method sendPhoto because I see that there's only one parameter, but, how can I use photo option?
Thank you.

**Comment by AceSpades** [comment]
I'm arrived here:
```javascript
bot.sendPhoto({chat_id: 'id-here', files: {photo: {filename: 'filename-here.ext', stream: undefined}}}, function (err){
 if(err) console.log(err);
 console.log(" --> Image sent");
});
```
but i don't know what have to be placed in files.photo.stream

**Comment by Kaos1337** [comment]
It doesn't work for me, I already have a png image in local but that written method example doesn't send it.

**Comment by Kaos1337** [comment]
Works, thx.
