### ISSUE TITLE
Channel support and new Chat type?

### ISSUE THREAD

**Issue by fivepointseven** [depoio/node-telegram-bot#54]
Hi. Are you planning to add channel support and new Chat field type in Message?

**Comment by shernshiou** [comment]
@fivepointseven I will implement it by this week.

https://core.telegram.org/bots/api#chat

**Comment by shernshiou** [comment]
Chat field type is working normally.
I am able to put my bot into a channel but the bot does not receive any messages. Any idea?

**Comment by fivepointseven** [comment]
@shernshiou are bots actually supposed to see channel messages? I thought they're intended as administrators...

**Comment by shernshiou** [comment]
@fivepointseven from the chat field, there are information about channel title and channel chat type. I suppose bots can view it. I will test further. Appreciate if more people can help :)
