### ISSUE TITLE
Send gif

### ISSUE THREAD

**Issue by gielcobben** [depoio/node-telegram-bot#55]
Hello I want to send a gif file like this:

    bot.sendDocument({
        chat_id: id,
        document: request(original_url).pipe(fs.createReadStream("image.gif"))
    });

But I keep getting this message:

    .../node_modules/node-telegram-bot/lib/Bot.js:700
        if (options.files.stream) {
                         ^

    TypeError: Cannot read property 'stream' of undefined

**Comment by shernshiou** [comment]
@gielcobben 
if you would like to send as stream

```javascript
bot.sendDocument({
  chat_id: id,
  files: {
    stream: fs.createReadStream("image.gif")
  }
});
```

**Comment by gielcobben** [comment]
Great, thank you.
