### ISSUE TITLE
Error HTTP 409

### ISSUE THREAD

**Issue by kaminoo** [depoio/node-telegram-bot#57]
Hi everyone.
Am I the only one getting a ton of 409 errors from Telegram?
It's stated somewhere on the web that this is probably when trying to use multiple bots at the same time, but the case is I'm only running one instance of each one that I have.
Every couple of minutes I get this error and restart the polling.

I did find a probable bug on the Bot, that in the polling the getUpdates gets a 60 seconds timeout, but the actual request call is only 6 seconds (6000ms). I increased to 70000ms to make sure Telegram times out first, but I still get the same problems.

I run at least 10 bots at the same time.

Anyone else having this problem?
Seba

**Comment by shernshiou** [comment]
Did you use the same token? @kaminoo

**Comment by kaminoo** [comment]
No of course not. Different bots. Different tokens.

**Comment by shernshiou** [comment]
Fixes by @kaminoo a40e8e56f479f7a698eeaf12565732a02f3a790b
