### ISSUE TITLE
sendMessage with ReplyKeyboardMarkup question

### ISSUE THREAD

**Issue by Liryna** [depoio/node-telegram-bot#6]
Hi !

I try to send a message with custom keyboard as reply.

```
bot.sendMessage({chat_id: myid,
                             text: "Who to write ?",
                             reply_markup: {
                                 keyboard: [ ["hello"], ["world"] ],
                             }
                                    }, function(err, ret) {
                                        if(err) return console.error(err);
                                    })
 
```
I get the message "Who to write ?" and I see that the client is waiting a command but none of the options are shown.
Am i doing something wrong ?

**Comment by shernshiou** [comment]
Looking into it ya..

**Comment by shernshiou** [comment]
@Liryna can you try again? Its working at my side.

**Comment by Liryna** [comment]
Yes it work !
But you should also add it for sendPhoto, sendAudio, ...
Thank a lot :) !

**Comment by shernshiou** [comment]
Thanks. I will now add it to sendPhoto and sendAudio since you confirmed it works.
