### ISSUE TITLE
sendPhoto throwing error

### ISSUE THREAD

**Issue by fivepointseven** [depoio/node-telegram-bot#8]
I do as said in one of closed issues:
```javascript
bot.sendPhoto({
	chat_id: message.chat.id,
	files: {
		photo: {
			filename: 'test.jpg',
			stream: fs.createReadStream('test.jpg')
		}
	}
});
```

```
 if (options.filename || value.path) {
                                 ^
TypeError: Cannot read property 'path' of undefined
```

What am I doing wrong?

**Comment by shernshiou** [comment]
@fivepointseven I tried to fix it with the recent commit, can you try? Appreciate your feedback.

**Comment by fivepointseven** [comment]
@shernshiou works flawlessly now! Thanks!

**Comment by shernshiou** [comment]
@fivepointseven Thanks!.. It is under development, there will be bugs here and there. I am very sorry.

**Comment by fivepointseven** [comment]
@shernshiou 
Yep, 2 minutes after I updated to 0.0.12 you committed 0.0.13 :)
I'm actively developing a few bots with this, so I'll report any found bugs :) 
Thanks for quick response!
